name       : cups-filters
version    : 1.3.0
release    : 1
source     :
    - https://www.openprinting.org/download/cups-filters/cups-filters-1.3.0.tar.xz : 61b669809dda352a427546e09de5a68a3d960c7646ef5c590772d4aa1b445995
license    : GPL-2.0
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(glib-2.0)
    - pkgconfig(avahi-glib)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(poppler)
    - pkgconfig(zlib)
    - pkgconfig(libqpdf)
    - pkgconfig(dbus-1)
    - pkgconfig(libtiff-4)
    - pkgconfig(ijs)
    - libjpeg-turbo-devel
    - cups-devel
setup      : |
    %configure --without-rcdir \
               --disable-static \
               --with-gs-path=/usr/bin/gs \
               --with-pdftops-path=/usr/bin/gs
build      : |
    %make
install    : |
    %make_install
