name       : cups-filters
version    : 1.17.8
release    : 17
source     :
    - https://openprinting.org/download/cups-filters/cups-filters-1.17.8.tar.xz : 9acefd72f8e6a6e5fb6e80d37aad8c712c326bf484afb735e8ff7d7b86975870
license    :
    - GPL-2.0
    - MIT
component  : desktop.core
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(dbus-1)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(ijs)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libqpdf)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - cups-devel
    - dejavu-fonts-ttf # make check
    - ghostscript
    - libjpeg-turbo-devel
replaces   :
    - foomatic-filters
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-absolute-paths-for-font-directory-and-do-not-mak.patch
    %reconfigure --without-rcdir \
                 --disable-static \
                 --disable-mutool \
                 --enable-imagefilters \
                 --enable-auto-setup-driverless \
                 --with-gs-path=/usr/bin/gs \
                 --with-pdftops-path=/usr/bin/gs \
                 --with-fontdir=/usr/share/fonts/conf.d \
                 --with-cups-rundir=/run/cups \
                 --with-test-font-path=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
build      : |
    %make
install    : |
    %make_install

    # Install the cups-browsed.service systemd unit file from the upstream sources
    install -Dm00644 utils/cups-browsed.service $installdir/%libdir%/systemd/system/cups-browsed.service
check      : |
    %make check
