name       : cups-filters
version    : 1.27.2
release    : 54
source     :
    - https://github.com/OpenPrinting/cups-filters/releases/download/release-1-27-2/cups-filters-1.27.2.tar.xz : f7ad7ccda10340e468b9a45429baa54b84af8a170016cab89a3b5e404a97fa25
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.core
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(dbus-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libqpdf)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler)
    - cups-devel
    - dejavu-fonts-ttf # make check
    - ghostscript
rundeps    :
    - poppler-utils
replaces   :
    - foomatic-filters
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-absolute-paths-for-font-directory-and-do-not-mak.patch
    %patch -p1 < $pkgfiles/0001-utils-Enable-driverless-configuration-automagically.patch
    %patch -p1 < $pkgfiles/0002-utils-Fix-broken-systemd-unit.patch

    %reconfigure --without-rcdir \
        --disable-static \
        --disable-mutool \
        --enable-pclm \
        --enable-imagefilters \
        --enable-auto-setup-driverless \
        --with-fontdir=/usr/share/fonts/conf.d \
        --with-cups-rundir=/run/cups \
        --with-test-font-path=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
build      : |
    %make
install    : |
    %make_install

    # Install the cups-browsed.service systemd unit file from the upstream sources
    install -D -m 00644 utils/cups-browsed.service $installdir/%libdir%/systemd/system/cups-browsed.service

    # Enable to start on boot
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../cups-browsed.service $installdir/%libdir%/systemd/system/multi-user.target.wants/.
check      : |
    %make check
