name       : cups-filters
version    : 1.16.1
release    : 16
source     :
    - https://openprinting.org/download/cups-filters/cups-filters-1.16.1.tar.xz : 32da05c059a8f7f74eb78abdfffe1dddad9dd8439771e2232be7aef71a4443a3
license    :
    - GPL-2.0
    - MIT
component  : desktop.core
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(dbus-1)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(ijs)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libqpdf)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - pkgconfig(zlib)
    - cups-devel
    - dejavu-fonts-ttf # make check
    - ghostscript
    - libjpeg-turbo-devel
replaces   :
    - foomatic-filters
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-absolute-paths-for-font-directory-and-do-not-mak.patch
    %reconfigure --without-rcdir \
                 --disable-static \
                 --disable-mutool \
                 --enable-imagefilters \
                 --enable-auto-setup-driverless \
                 --with-gs-path=/usr/bin/gs \
                 --with-pdftops-path=/usr/bin/gs \
                 --with-fontdir=/usr/share/fonts/conf.d \
                 --with-test-font-path=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
build      : |
    %make
install    : |
    %make_install

    # Install the cups-browsed.service systemd unit file from the upstream sources
    install -Dm644 utils/cups-browsed.service $installdir%libdir%/systemd/system/cups-browsed.service
check      : |
    %make check

