name       : cups-filters
version    : 1.28.15
release    : 71
source     :
    - https://github.com/OpenPrinting/cups-filters/releases/download/1.28.15/cups-filters-1.28.15.tar.gz : 614e053404bb833f78e1edf077f7759d27e475a212eb9a3bd3eac2cfec8bb6c1
homepage   : https://github.com/OpenPrinting/cups-filters
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - MIT
component  : desktop.core
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(dbus-1)
    - pkgconfig(glib-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libqpdf)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(poppler)
    - cups-devel
    - dejavu-fonts-ttf # make check
    - ghostscript
rundeps    :
    - poppler-utils
replaces   :
    - foomatic-filters
setup      : |
    %apply_patches

    %reconfigure --without-rcdir \
        --disable-static \
        --disable-mutool \
        --enable-pclm \
        --enable-imagefilters \
        --enable-auto-setup-driverless \
        --with-fontdir=/usr/share/fonts/conf.d \
        --with-cups-rundir=/run/cups \
        --with-test-font-path=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
build      : |
    %make
install    : |
    %make_install

    # Install the cups-browsed.service systemd unit file from the upstream sources
    install -Dm00644 utils/cups-browsed.service $installdir/%libdir%/systemd/system/cups-browsed.service

    # Enable to start on boot
    install -dm00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../cups-browsed.service $installdir/%libdir%/systemd/system/multi-user.target.wants/.
check      : |
    %make check
