name       : cups-filters
version    : 1.4.0
release    : 7
source     :
    - https://www.openprinting.org/download/cups-filters/cups-filters-1.4.0.tar.xz : 0aa63f82a3feb5c46136b917722ee1565b4c1e2e533db4716f62d31e29c6579a
license    : GPL-2.0
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(glib-2.0)
    - pkgconfig(avahi-glib)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(poppler)
    - pkgconfig(zlib)
    - pkgconfig(libqpdf)
    - pkgconfig(dbus-1)
    - pkgconfig(libtiff-4)
    - pkgconfig(ijs)
    - libjpeg-turbo-devel
    - cups-devel
replaces   :
    - foomatic-filters
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-absolute-paths-for-font-directory-and-do-not-mak.patch
    autoreconf -vfi
    %configure --without-rcdir \
               --disable-static \
               --with-gs-path=/usr/bin/gs \
               --with-pdftops-path=/usr/bin/gs \
               --with-fontdir=/usr/share/fonts/conf.d
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/share/man/man1/foomatic-rip.1
    rm -v $installdir/usr/lib/cups/filter/foomatic-rip
    rm -v $installdir/usr/bin/foomatic-rip
