name       : cups-filters
version    : 1.14.0
release    : 13
source     :
    - https://openprinting.org/download/cups-filters/cups-filters-1.14.0.tar.xz : 7aa4274df6e6d9b5ff66e079d78dde8254570367c745025e58bc6194371fa5ec
license    : GPL-2.0
component  : desktop.core
summary    : Core CUPS Filters
description: |
    The CUPS Filters package contains backends, filters and other software that was once part of the core CUPS distribution but is no longer maintained by Apple Inc.
builddeps  :
    - ghostscript
    - pkgconfig(libpng)
    - pkgconfig(glib-2.0)
    - pkgconfig(avahi-glib)
    - pkgconfig(gio-2.0)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(poppler)
    - pkgconfig(zlib)
    - pkgconfig(libqpdf)
    - pkgconfig(dbus-1)
    - pkgconfig(libtiff-4)
    - pkgconfig(ijs)
    - libjpeg-turbo-devel
    - cups-devel
replaces   :
    - foomatic-filters
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-absolute-paths-for-font-directory-and-do-not-mak.patch
    autoreconf -vfi
    %configure --without-rcdir \
               --disable-static \
               --disable-mutool \
               --with-gs-path=/usr/bin/gs \
               --with-pdftops-path=/usr/bin/gs \
               --with-fontdir=/usr/share/fonts/conf.d
build      : |
    %make
install    : |
    %make_install
